### ISSUE TITLE
model

### ISSUE THREAD

**Issue by jvdborre** [llooker/snowflake-usage-block#1]
Hi guys,
in a recent update, Snowflake introduced the Snowflake database that does what the code below (from the install instructions) does.
```
use role accountadmin;
show shares; -- this should return snowflake.account_usage
create database snowflake_account_usage from share snowflake.account_usage;
grant imported privileges on database snowflake_account_usage to role <preferred_role>;
use role <preferred_role>;
use schema snowflake_account_usage.account_usage;
show views;
```

Now that's one step less to install this block!

**Comment by brettguenther** [comment]
Resolved via https://github.com/llooker/snowflake-usage-block/commit/5e312bcd24191190e61c3bdd9d7294ad3cbb08e1
